# Generated by scripts/update_pomodoro.py from verified GitHub release assets.
cask "pomodoro-blocker" do
  version "0.1.3"
  sha256 "035b8cf940f0aed05cb7cc72abc8d5cef6776cede68cb7c7b686b0b83489d05a"

  url "https://github.com/marcusmalloc/pomodoro-blocker/releases/download/v#{version}/PomodoroBlocker-#{version}-universal.zip"
  name "Pomodoro Blocker"
  desc "Menu bar focus timer with app and website blocking"
  homepage "https://github.com/marcusmalloc/pomodoro-blocker"

  depends_on macos: :sonoma

  app "PomodoroBlocker.app"

  uninstall quit: "com.marcusmalloc.pomodoroblocker"

  zap trash: "~/Library/Preferences/com.marcusmalloc.pomodoroblocker.plist"

  caveats <<~EOS
    Open PomodoroBlocker from Applications after installing.
    If macOS blocks the first launch, choose Open Anyway in
    System Settings > Privacy & Security.
  EOS
end
