# Generated by scripts/update_pomodoro.py from verified GitHub release assets.
cask "pomodoro-blocker" do
  version "0.1.2"
  sha256 "173b01afdb28e60b6c97f18a8e6e92d027d15f5fe8d299a3bf592df1a077b60a"

  url "https://github.com/marcusmalloc/pomodoro-blocker/releases/download/v#{version}/PomodoroBlocker-#{version}-universal.zip"
  name "Pomodoro Blocker"
  desc "Menu bar focus timer with app and website blocking"
  homepage "https://github.com/marcusmalloc/pomodoro-blocker"

  depends_on macos: :sonoma

  app "PomodoroBlocker.app"

  uninstall quit: "com.marcusmalloc.pomodoroblocker"

  zap trash: "~/Library/Preferences/com.marcusmalloc.pomodoroblocker.plist"

  caveats <<~EOS
    Open PomodoroBlocker from Applications after installing.
    If macOS blocks the first launch, choose Open Anyway in
    System Settings > Privacy & Security.
  EOS
end
