#!/usr/bin/env python3
"""Verify the latest stable Pomodoro release and update only its cask."""

import hashlib
import json
import os
from pathlib import Path
import re
import sys
import time
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen


REPOSITORY = "marcusmalloc/pomodoro-blocker"
LATEST_RELEASE = f"https://api.github.com/repos/{REPOSITORY}/releases/latest"
RELEASE_DOWNLOAD = f"https://github.com/{REPOSITORY}/releases/download"
VERSION = r"(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)"
CASK = Path(__file__).resolve().parents[1] / "Casks/pomodoro-blocker.rb"


def read_url(url):
    headers = {"User-Agent": "pomodoro-homebrew-updater"}
    if url == LATEST_RELEASE:
        headers["Accept"] = "application/vnd.github+json"
        headers["X-GitHub-Api-Version"] = "2022-11-28"
        if token := os.environ.get("GITHUB_TOKEN"):
            headers["Authorization"] = f"Bearer {token}"
    request = Request(url, headers=headers)
    for attempt in range(4):
        try:
            with urlopen(request, timeout=30) as response:
                return response.read()
        except HTTPError as error:
            if error.code not in (408, 429, 500, 502, 503, 504) or attempt == 3:
                raise
        except URLError:
            if attempt == 3:
                raise
        time.sleep(2 ** (attempt + 1))


def latest_release():
    try:
        return json.loads(read_url(LATEST_RELEASE))
    except HTTPError as error:
        if error.code == 404:
            return None  # The app has not published its first release yet.
        raise


def version_tuple(version):
    if not re.fullmatch(VERSION, version):
        raise ValueError(f"Expected a stable N.N.N version, got {version!r}")
    return tuple(map(int, version.split(".")))


def asset_url(release, name, expected_url):
    assets = [asset for asset in release["assets"] if asset["name"] == name]
    if len(assets) != 1 or assets[0].get("state") != "uploaded":
        raise ValueError(f"Expected one uploaded release asset: {name}")
    if assets[0].get("browser_download_url") != expected_url:
        raise ValueError(f"Unexpected download URL for {name}")
    return expected_url


def render_cask(version, checksum):
    return f'''# Generated by scripts/update_pomodoro.py from verified GitHub release assets.
cask "pomodoro-blocker" do
  version "{version}"
  sha256 "{checksum}"

  url "https://github.com/{REPOSITORY}/releases/download/v#{{version}}/PomodoroBlocker-#{{version}}-universal.zip"
  name "Pomodoro Blocker"
  desc "Menu bar focus timer with app and website blocking"
  homepage "https://github.com/{REPOSITORY}"

  depends_on macos: :sonoma

  app "PomodoroBlocker.app"

  uninstall quit: "com.marcusmalloc.pomodoroblocker"

  zap trash: "~/Library/Preferences/com.marcusmalloc.pomodoroblocker.plist"

  caveats <<~EOS
    Open PomodoroBlocker from Applications after installing.
    If macOS blocks the first launch, choose Open Anyway in
    System Settings > Privacy & Security.
  EOS
end
'''


def update_cask(release, destination=CASK):
    if release is None or release.get("draft") or release.get("prerelease"):
        print("No stable release to publish.")
        return False
    tag = release["tag_name"]
    if not tag.startswith("v"):
        raise ValueError(f"Expected a vN.N.N release tag, got {tag!r}")
    version = tag[1:]
    target_version = version_tuple(version)
    if destination.exists():
        current = re.search(r'^  version "([^"]+)"$', destination.read_text(), re.M)
        if current is None:
            raise ValueError("Cannot read the existing cask version")
        if target_version <= version_tuple(current[1]):
            print("Pomodoro cask is already up to date.")
            return False

    archive = f"PomodoroBlocker-{version}-universal.zip"
    checksum_file = archive + ".sha256"
    base_url = f"{RELEASE_DOWNLOAD}/{tag}"
    archive_url = asset_url(release, archive, f"{base_url}/{archive}")
    checksum_url = asset_url(release, checksum_file, f"{base_url}/{checksum_file}")
    checksum_text = read_url(checksum_url).decode("ascii")
    match = re.fullmatch(r"([0-9a-f]{64})  " + re.escape(archive) + r"\n?", checksum_text)
    if match is None:
        raise ValueError("Checksum file does not identify the expected archive")
    checksum = match[1]
    if hashlib.sha256(read_url(archive_url)).hexdigest() != checksum:
        raise ValueError("Release archive checksum does not match")

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(render_cask(version, checksum))
    print(f"Updated Pomodoro cask to {version}.")
    return True


if __name__ == "__main__":
    try:
        update_cask(latest_release())
    except (HTTPError, URLError, ValueError, KeyError, TypeError, OSError) as error:
        sys.exit(f"Pomodoro cask update failed: {error}")
